image: registry.manatree.io/rvanduijnhoven/maven-python-dockerimage

before_script:
  - mkdir -p /root/.m2 && cp settings.xml "$_"

stages:
  - build

Build maven projects:
  stage: build
  tags:
    - linux_docker
  script:
    - cd releng/{parent-dir}
	- mvn -e clean install
  artifacts:
    when: always
    paths:
      - "code/**/target/*.jar"
