image: registry.manatree.io/rvanduijnhoven/maven-python-dockerimage

before_script:
  - chmod -R +x ./scripts

stages:
  - build
#  - publish

Build maven projects:
  stage: build
  tags:
    - linux_docker
  script:
    - cd releng/org.espilce.commons.parent
    - mvn clean install -s ../../settings.xml -Ppublish,merge-existing-repository -Dmaven.test.failure.ignore=true
  artifacts:
    when: always
    paths:
      - "component/*/*/target/*.jar"
#publish:
#  stage: publish
#  tags:
#    - linux_docker
#  script:
#    - ./scripts/publish.py
#  allow_failure: true
